config/routes.rb
Rails.application.routes.draw do

mount ActionCable.server => '/cable'

  devise_for :health_centers
  devise_for :users
  devise_for :hospitals

devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

devise_scope :health_center do
  post 'health_centers/guest_sign_in', to: 'health_centers/sessions#new_guest'
end

devise_scope :hospital do
  post 'hospitals/guest_sign_in', to: 'hospitals/sessions#new_guest'
end


scope "(:locale)", locale: /en|ja/ do
  root "user/homes#top"
end
  get '/:locale' => "static_pages#home"

namespace :user do

  resources :users, only: [:show, :edit, :update, :destroy]
  put "/users/:id/hide" => "users#hide", as: "users_hide"
  resources :health_centers, only: [:index, :show] do
    get "autocomplete_health_center_name", on: :collection
  end
  get "user_healths/confirm" => "user_healths#error"
  resources :user_healths, only: [:new, :create, :index, :show]
  post "user_healths/confirm" => "user_healths#confirm"
  get "health_centers/search" => "health_centers#search"
  get "/:health_center_id/room/" => "rooms#show", as: "chat_room"
  get "/messages/notification" => "messages#notification"
end

namespace :health_center do

  get "/rooms/search" => "rooms#search"
  resources :users, only: [:index, :show]
  get "/users/search" => "users#search"
  get "/:user_id/room/" => "rooms#show", as: "chat_room"
  get "/rooms" => "rooms#index", as: "chat_rooms"
  resources :user_healths, only: [:index, :show]
  resources :examinations, only: [:index, :show]
  resources :hospitals, only: [:index, :show]
  get "/examinations/search" => "examinations#search"


end

namespace :hospital do

  resources :users, only: [:index, :show]
  resources :health_centers, only: [:index, :show]
  get "examination/comfirm" => "examinations#error"
  resources :examinations, only: [:index, :new, :create, :show]
  post "examination/confirm" => "examinations#confirm"
  get "/health_centers/search" => "health_centers#search"
  get "/users/search" => "users#search"

end

end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }

  enum from: {
    user: 0,
    health_center: 1
  }, _prefix: true

  belongs_to :user, optional: true
  belongs_to :health_center, optional: true
  belongs_to :room

  validates :user_id, allow_blank: true, length: { in: 1..200 }
  validates :health_center_id, allow_blank: true, length: { in: 1..200 }
  validates :room_id, presence: true
  validates :message, presence: true

end

app/controllers/health_center/messages_controller.rb
class HealthCenter::MessagesController < ApplicationController
  before_action :authenticate_health_center!
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  def create
    @room = Room.find(params[:id])
    @message = @room.message.build(message_params)
    @message.user_id = current_user.id
    @message_room = @message.room
    @healthcenter = @message.health_center
    if massage.save
      @message_room.create_notification_message!(current_user, @message.id)
      reder :index
    end
  end

  def notification
    @room = Room.find(params[:room_id])
    if params[:who] == 'user'
      msgs = Message.where(room_id: @room.id).where(user_id: current_user.id)
      msgs.where(user_checked: false).update(user_checked: true)
    elsif params[:who] == 'healthcenter'
      msgs = Message.where(room_id: @room.id).where(health_center_id: current_health_center.id)
      msgs.where(healthcenter_checked: false).update(healthcenter_checked: true)
    end
  end
end

app/helpers/health_center/messages_helper.rb
module HealthCenter::MessagesHelper
  # def uncheck_notifications
  #   @messages = current_user.passive_notifications.where(checked: false)
  # end
end

app/helpers/user/messages_helper.rb
module User::MessagesHelper
  
  # def uncheck_notifications
  #    @messages = current_user.passive_notifications.where(checked: false)
  # end
end

app/views/messages/_message.html.erb
<div class="message">
    <div class="my-message <%= message.from %>">
    <p class="pl-5 pt-5"><%= link_to message.user.full_name,health_center_user_path(message.user),class: "Editlink user_link" %>
    <%= link_to message.health_center.name,user_health_center_path(message.health_center), class: "Editlink health_center_link" %>
    <%= message.created_at.strftime('%m/%d %H:%M') %><br>
    <%= message.message %></p>
     </div>
</div>

app/views/messages/_room_channel.html.erb
<!--クラインとサイドの処理を記載-->
<script>
document.addEventListener("turbolinks:load", function(){
appRoom = App.cable.subscriptions.create("RoomChannel", {
  connected: function() {
    // Called when the subscription is ready for use on the server
  },

  disconnected: function() {
    // Called when the subscription has been terminated by the server
  },

  received: function(data) {
    const messages = document.getElementById('messages');
    const name = messages.getAttribute('name');
    const from = messages.getAttribute('from');
    // var newDiv = document.createElement("div");
    // if messages.user == current_user "me"
    // else "other"
    messages.insertAdjacentHTML('beforeend', data['message']);
    if (data['from'] == from){
      $("."+from).css('text-align','right');
      $("."+from).children('p').removeClass('pl-5 pt-5');
      $("."+from).children('p').addClass('pr-5 pt-4');
      $("."+from).children('p').children(".Editlink").hide();
    }
    else{
      $("."+from+"_link").hide();
    }
    // messages.insertAdjacentHTML("me", data['message']);
    checked()

  },

  speak: function(message) {
    const room_id = document.getElementById('messages').getAttribute('room_id');
    const from = document.getElementById('messages').getAttribute('from');
    return this.perform('speak', {message: message, room_id: room_id, checked:1, from: from});
  }
});

window.addEventListener("keypress", function(e) {
  if (e.keyCode === 13) {
    appRoom.speak(e.target.value);
    e.target.value = '';
    e.preventDefault();
  }
})

function checked(){
  const room_id = document.getElementById('messages').getAttribute('room_id');

	var url = '/user/messages/notification?room_id=' + room_id + '&who=';
	<% if user_signed_in? %>
		url = url +'user';
	<% else %>
		url = url +'healthcenter';
	<% end %>

	$.ajax({
            url: url,
            type: 'GET',
            dataType: 'html'
        }).done(function(data){

        }).fail(function(data){

        });
    };
})
</script>