config/routes.rb
Rails.application.routes.draw do

mount ActionCable.server => '/cable'

  devise_for :health_centers
  devise_for :users
  devise_for :hospitals

devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

devise_scope :health_center do
  post 'health_centers/guest_sign_in', to: 'health_centers/sessions#new_guest'
end

devise_scope :hospital do
  post 'hospitals/guest_sign_in', to: 'hospitals/sessions#new_guest'
end


scope "(:locale)", locale: /en|ja/ do
  root "user/homes#top"
end
  get '/:locale' => "static_pages#home"

namespace :user do

  resources :users, only: [:show, :edit, :update, :destroy]
  put "/users/:id/hide" => "users#hide", as: "users_hide"
  resources :health_centers, only: [:index, :show] do
    get "autocomplete_health_center_name", on: :collection
  end
  get "user_healths/confirm" => "user_healths#error"
  resources :user_healths, only: [:new, :create, :index, :show]
  post "user_healths/confirm" => "user_healths#confirm"
  get "health_centers/search" => "health_centers#search"
  get "/:health_center_id/room/" => "rooms#show", as: "chat_room"
  get "/messages/notification" => "messages#notification"
end

namespace :health_center do

  get "/rooms/search" => "rooms#search"
  resources :users, only: [:index, :show]
  get "/users/search" => "users#search"
  get "/:user_id/room/" => "rooms#show", as: "chat_room"
  get "/rooms" => "rooms#index", as: "chat_rooms"
  resources :user_healths, only: [:index, :show]
  resources :examinations, only: [:index, :show]
  resources :hospitals, only: [:index, :show]
  get "/examinations/search" => "examinations#search"


end

namespace :hospital do

  resources :users, only: [:index, :show]
  resources :health_centers, only: [:index, :show]
  get "examination/comfirm" => "examinations#error"
  resources :examinations, only: [:index, :new, :create, :show]
  post "examination/confirm" => "examinations#confirm"
  get "/health_centers/search" => "health_centers#search"
  get "/users/search" => "users#search"

end

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum gender: {
    man: 0,
    woman: 1
  }

  has_many :user_healths
  has_many :rooms
  has_many :messages, dependent: :destroy
  has_many :examinations ,dependent: :destroy

  has_many :active_notifications, class_name: 'Message', foreign_key: 'user_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Message', foreign_key: 'health_center_id', dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :gender, presence: true
  validates :age, inclusion: { in: 1..99 }
  validates :postcode, presence: true, length: { is: 7 }
  validates :address_city, presence: true
  validates :address_street, presence: true
  validates :address_building, presence: true
  validates :phone_number, presence: true, length: { in: 10..11 }
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :is_deleted, inclusion: { in: [true, false] }

  def self.search(search)
    if search
        User.where(['first_name_kana LIKE? OR last_name_kana LIKE? OR phone_number LIKE?', "%#{search}%","%#{search}%","%#{search}%"])
    else
        User.all
    end
  end

  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com', last_name: "田中", first_name: "太郎", last_name_kana: "タナカ", first_name_kana: "タロウ", postcode: "1234567", address_city: "東京都", address_street: "渋谷区", address_building: "神南1丁目19-11", phone_number: "08034268377", gender: "man", age: "27", is_deleted: "false") do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

end

app/controllers/health_center/users_controller.rb
class HealthCenter::UsersController < ApplicationController
  
  before_action :authenticate_health_center!

  
  def index
    # @messages = current_health_center.messages
    # user_ids = @messages.map(&:user_id)
    # @users = User.where(id: user_ids).search(params[:search]).distinct.page(params[:page]).per(6)
    # #上記は「この保健所に紐づいた」ユーザー一覧
    @users = User.search(params[:search]).page(params[:page]).per(6)

  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/hospital/users_controller.rb
class Hospital::UsersController < ApplicationController

  def index
    #同じ市区町村にいる人の一覧から検索
    @users = User.search(params[:search]).page(params[:page]).per(6)
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/user/chats_controller.rb
class User::ChatsController < ApplicationController
  
  
  
  
end

app/controllers/user/health_centers_controller.rb
class User::HealthCentersController < ApplicationController

  autocomplete :health_center, :name, full: true

  
  def index
    @health_centers = HealthCenter.search(params[:search]).page(params[:page]).per(6)
  end

  def show
    @health_center = HealthCenter.find(params[:id])
    # @checked = false
    #   if Message.where(user_id: current_user.id).last.updated_at <= Message.where(health_center_id: @health_center.id).last.created_at
    #     @checked = true
    #   end
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  def create
    @room = Room.find(params[:id])
    @message = @room.message.build(message_params)
    @message.user_id = current_user.id
    @message_room = @message.room
    @healthcenter = @message.health_center
    if massage.save
      @message_room.create_notification_message!(current_user, @message.id)
      reder :index
    end
  end

  def notification
    @room = Room.find(params[:room_id])
    if params[:who] == 'user'
      msgs = Message.where(room_id: @room.id).where(user_id: current_user.id)
      msgs.where(user_checked: false).update(user_checked: true)
    elsif params[:who] == 'healthcenter'
      msgs = Message.where(room_id: @room.id).where(health_center_id: current_health_center.id)
      msgs.where(healthcenter_checked: false).update(healthcenter_checked: true)
    end
  end
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController
  before_action :authenticate_user!

  # def create
  #   @message = Message.new
  #   ActionCable.server.broadcast "room_channel", message: @message
  #   @message.create(message_params)
  # end

  def show
    @room = current_user.rooms.find_by(health_center_id: params[:health_center_id])
    unless @room
      @room = current_user.rooms.create(health_center_id: params[:health_center_id])
    end
    @messages = Message.where(room_id: @room.id)
    @messages.update(user_checked: true)
    @health_center = HealthCenter.find(params[:health_center_id])
    # gon.user_kind =  if user_signed_in?
		  #                   'user'
	   #                 else
		  #                   'healthceter'
	   #                  end
  end

  # private

  # def message_params
  #   params.permit(:message, :checked)
  # end
end

app/controllers/user/user_healths_controller.rb
class User::UserHealthsController < ApplicationController

  before_action :authenticate_user!

  def new
    @user = current_user
    @user_health = @user.user_healths.build
  end

  def confirm
    @user_health = UserHealth.new
    @user_health.temperature = params[:temperature]
    @user_health.condition = params[:condition]
    @user_health.transportation = params[:transportation]
    if params[:want_examination] == "1"
      want_examination_value = true
    elsif params[:want_examination] == "0"
      want_examination_value = false
    end
    @user_health.want_examination = want_examination_value
    @user_health.health_center_id = params[:health_center_id]
  end

  def create
    @user_health = UserHealth.new(user_health_params)
    if params[:want_examination] == "1"
      want_examination_value = true
    elsif params[:want_examination] == "0"
      want_examination_value = false
    end
    @user_health.user_id = current_user.id
    @user_health.magnitude = Language.get_data(user_health_params[:condition])  #この行を追加
    if @user_health.save
      redirect_to user_user_health_path(@user_health)
    else
      render "new"
    end
  end

  def error
    redirect_to new_user_user_health_path
  end

  def index
    @user_healths = current_user.user_healths
  end

  def show
    @user_health = UserHealth.find(params[:id])
  end

  private

  def user_health_params
    params.require(:user_health).permit(:temperature, :condition, :transportation, :want_examination, :health_center_id)
  end

end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @room = Room.find_by(user_id: current_user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update!(user_params)
      redirect_to user_user_path
    else
      render :edit
    end
  end

  def hide
    user = current_user
    user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :first_name_kana, :last_name_kana, :gender, :age, :email, :postcode, :address_city, :address_street, :address_building, :phone_number, :is_deleted)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]


  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/health_center/users_helper.rb
module HealthCenter::UsersHelper
end

app/helpers/hospital/users_helper.rb
module Hospital::UsersHelper
end

app/helpers/user/chats_helper.rb
module User::ChatsHelper
end

app/helpers/user/health_centers_helper.rb
module User::HealthCentersHelper
end

app/views/user/users/edit.html.erb
<div class="container">
  <div class="row mx-auto my-4">
    <h2 class="title"><%= t :edit_mypage %></h2>
  </div>
    <% if @user.errors.any? %>
      <p class="validates-errors">入力に誤りがあります</p>
    <% end %>

<div class="container edit-contents pt-3">
  <div class="row pl-5 pt-3">
    <%= form_with model: @user, url: user_user_path, method: :patch, local:true do |f| %>
      <div class="field my-3">
        <%= f.label :last_name, "#{ t :last_name }" %><br />
        <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
      </div>
      <div class="field my-3">
        <%= f.label :first_name,"#{ t :first_name }" %><br />
        <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
      </div>
      <div class="field my-3">
        <%= f.label :last_name_kana,"#{ t :last_name_kana }" %><br />
        <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %>
      </div>
      <div class="field my-3">
        <%= f.label :first_name_kana,"#{ t :first_name_kana }" %><br />
        <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %>
      </div>
      <div class="field my-3">
        <%= f.label :age,"#{ t :age }" %><br />
        <%= f.text_field :age, autofocus: true, autocomplete: "age" %>
      </div>
      <div class="field my-3">
        <%= f.label :email,"#{ t :email}" %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>
      <div class="field my-3">
        <%= f.label :postcode,"#{ t :postcode }" %><br />
        <%= f.text_field :postcode, autofocus: true, autocomplete: "post_code" %>
      </div>
      <div class="field my-3">
        <%= f.label :address_city,"#{ t :address_city }" %><br />
        <%= f.text_field :address_city, autofocus: true, autocomplete: "address_city" %>
      </div>
      <div class="field my-3">
        <%= f.label :address_street,"#{ t :address_street }" %><br />
        <%= f.text_field :address_street, autofocus: true, autocomplete: "address_street" %>
      </div>
      <div class="field my-3">
        <%= f.label :address_building,"#{ t :address_building }" %><br />
        <%= f.text_field :address_building, autofocus: true, autocomplete: "address_building" %>
      </div>
      <div class="field my-3">
        <%= f.label :phone_number,"#{ t :phone }" %><br />
        <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number" %>
      </div>
      <div class="actions my-3">
        <%= f.submit "#{ t :update }", class:"chat-button" %>
      </div>
    <div>
      <%= link_to user_users_hide_path(current_user), method: :put, "data-confirm" => "本当に退会しますか？", class: "btn btn-outline-danger" do %><%= t :withdrawal %><% end %>
    </div>
    <% end %>
</div>
</div>

app/views/user/users/show.html.erb
<div class="container">
  <div class="row mx-auto my-4">
    <h2 class="title"><%= t :mypage %></h2>
  </div>

<div class="container center-contents pt-3">
  <div class="row my-5 pt-3">
  <table class="table table-hover show-list">
    <tr>
      <th><%= t :name %></th>
      <td><%= @user.full_name %></td>
    </tr>
    <tr>
      <th><%= t :age %></th>
      <td><%= @user.age %></td>
    </tr>
    <tr>
      <th><%= t :phone %></th>
      <td><%= @user.phone_number %></td>
    </tr>
    <tr>
      <th><%= t :address %></th>
      <td><%= @user.address_city + @user.address_street + @user.address_building %></td>
    </tr>
    <tr>
      <th><%= t :email %></th>
      <td><%= @user.email %></td>
    </tr>
  </table>
</div>

<div>
  <div class="mb-5 pl-3">
    <% if @room %>
      <%= link_to user_chat_room_path(@room.health_center), class:"chat-button" do %><%= t :last_chat %><% end %>
      <%= link_to user_user_healths_path, class:"chat-button" do %><%= t :my_conditions %><% end %>
    <% else %>
      <%= link_to "チャット履歴", "", class:"chat-button disabled" %>
      <%= link_to "健康状態履歴",user_user_healths_path, class:"chat-button" %>
    <% end %>
    <div class="d-flex justify-content-end pr-5 mr-5 mb-2">
      <%= link_to edit_user_user_path, class:"btn btn-success" do %><%= t :edit %><% end %>
    </div>
  </div>
</div>
</div>
</div>